name    'Aethylred-apaxage'
version '0.1.1'
source 'https://github.com/Aethylred/apaxage'
author 'Aethylred'
license 'GPL3'
summary 'Sets up an Apaxy themed package repository'
description 'A puppet module for setting up an Apaxy themed package repository for both apt and yum.'
project_page 'https://github.com/Aethylred/apaxage'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'Aethylred/apaxy', '>= 0.1.1'
dependency 'palli/createrepo', '>= 0.9.3'
# dependency 'jtopjian/reprepro', '>= 1.0.3'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/vcsrepo', '>= 0.2.0'